productly/productly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')
    ),]

productly/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'
urlpatterns = [
    path('', views.index, name='index'),
    path('formulario', views.formulario, name='formulario'),
    path(
        '<int:producto_id>', 
        views.detalle, 
        name='detalle'),
]

productly/productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    creado_en = models.DateField(default=timezone.now)

    def __str__(self):
        return self.nombre

productly/productos/forms.py
from . import models
from django.forms import ModelForm, TextInput, NumberInput, Select, DateInput

class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria', 'creado_en']
        widgets = {
            'nombre': TextInput(attrs={'class': 'form-control'}),
            'stock': NumberInput(attrs={'class': 'form-control'}),
            'puntaje': NumberInput(attrs={'class': 'form-control'}),
            'categoria': Select(attrs={'class': 'form-control'}),
            'creado_en': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

productly/productos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect

from .forms import ProductoForm
from .models import Producto


# Create your views here.
def index(request):
    productos = Producto.objects.all()
    # productos = Producto.objects.filter(stock__gt=0)
    #print(productos)
    #return JsonResponse(list(productos), safe=False)
    return render(
        request, 
        'index.html', 
        context ={'productos': productos}
        )

def detalle(request, producto_id):
    # #return HttpResponse(f"Detalle del producto {producto_id}")
    # try:
    #     producto = Producto.objects.get(id=producto_id)
    # except Producto.DoesNotExist:
    #     return HttpResponse("Producto no encontrado", status=404)
    #     #raise Http404("Producto no encontrado")
    producto = get_object_or_404(Producto, id=producto_id)
    
    return render(
        request, 
        'detalle.html', 
        context ={'producto': Producto.objects.get(id=producto_id)}
        )

def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()
    
    return render(
        request, 
        'formulario.html', 
        {'form': form}
    )

productly/productos/templates/detalle.html
{% extends 'base.html' %}
{# Extiende la plantilla base #}

{% block content %}
<div>
    <h6>Producto: {{ producto.nombre }}</h6>
    <p>Categoria: {{ producto.categoria }}</p>
    <p>Stock: {{ producto.stock }}</p>
    <p>Puntaje: {{ producto.puntaje }}</p>
    <p>Creado: {{ producto.creado_en }}</p>
</div>

{% endblock %}

productly/productos/templates/formulario.html
{% extends 'base.html' %}

{% block content %}

<h1>Formulario de Producto</h1>

<form 
    novalidate
    action="{% url 'productos:formulario' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Guardar"/>
</form>

{% endblock %}

productly/productos/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Lista de Productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    {{ producto.nombre }}
                </a>
            </td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
            <td>{{ producto.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

productly/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
        crossorigin="anonymous"></script>
</body>

</html>

productly/templates/detalle.html
{% extends 'base.html' %}
{# Extiende la plantilla base #}

{% block content %}
{# Bloque de contenido #}
<div>
    <h6>{{ producto.nombre }}</h6>
    <p>Categoria: {{ producto.categoria }}</p>
    <p>Stock: {{ producto.stock }}</p>
    <p>Puntaje: {{ producto.puntaje }}</p>
    <p>Creado: {{ producto.creado_en }}</p>
</div>

{% endblock %}
{# Fin del bloque de contenido #}

productly/templates/form_snippet.html
{% for field in form %}
    {{ field.label_tag }}
    {{ field }}
    
    {% if field.errors %}
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
{% endfor %}